name: Code checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install poetry

      - name: Validate the structure of the pyproject.toml
        run: poetry check

      - name: Verify that poetry.lock is consistent with pyproject.toml
        run: poetry lock --check

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run flake8
        run: poetry run flake8 .

      - name: Run mypy
        run: poetry run mypy .